name: Full Stack CI/CD

on: [push, pull_request]

jobs:
  frontend:
    name: Frontend Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
  
  backend:
    name: Backend Build & Deploy
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Tests (optional)
        working-directory: ./backend
        if: github.ref == 'refs/heads/dev'
        run: pytest

      - name: Deploy Backend
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploy backend here using SSH or CLI tool"
